### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by notrexxx**
# Tic_Tac_Toe second Milestone

- Displaying prompts to users
- Getting user input
- Created basic game flow

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes:full_moon:
Hi team!
Nice one on adding a readme:clap::clap:. The project is well structured. However, we have some changes to make to enable us to make progress.

**Mandatory requirements**

- [x] the game tells which player turn it is (without computing who the winner is)
- [x] the game asks the player to select from available moves
- [x] the game informs the player if the selected move is invalid (without computing what an invalid move is)
- [x] the game informs the player if the selected move is a winning move (without computing the winning move)
- [x] the game informs the player if the selected move is a draw move (without computing draw)
- [x] the game repeats all actions for the next player's move

The Game should be able to perform all the above tasks. Currently, one can only enter just two moves and the game ends. 

[Optional ] 
There's a lot of redundant print statements under instructions when a player is trying to play the game. You can move these instructions to the readme.


Make the above-required changes and when you are ready, request for another review.
Kindly drop your questions :point_down: and tag my name or ping me on slack @ Eric Enaburekhan to respond.
Happing Coding:blush:
Eric Enaburekhan

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

### Hey @notrexxx & @ccobasi, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [x] game informs player if the selected move is invalid (without computing what an invalid move is). Your game accepts all inputs as valid inputs, including aphabets.
- [x] game informs player if the selected move is a winning move (without computing the winning move).
- [x] game informs player if the selected move is a draw move (without computing draw).
- [x] game repeats all actions for the next player's move
-  You can add methods for win and draw to help you with some of the above requirements.
```

game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end

```

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :red_circle: :recycle: 
-------------
Hello team!! :wave: great job working on the required changes :muscle: 
However, there are a few changes to make :hammer_and_wrench:  to full fit, this milestone see them below :eyes: :point_down: 
----------

- [x] Your pull request must be `user_interface` branch to `development` branch not to `main` branch. Remember you should work with GIt Flow. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) you can read about git-flow.
- [x] Improve your commit messages, remember that you should write your commits in the imperative, [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read how to write excellent commit messages, [Check here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) if you need to change your commit messages. 
- [x] [REQUIRED] game displays board after the player move (without computing which spots on the board are taken), the game is not showing the board after every player move, remember that is not necessary that the board shows the move made it. It is only showing the board at the end of the game. 
----------------
Make the required changes :point_up: and send it again for another review. :smile: 
HAPPY CODDING!!

**Review by GzimAsani — APPROVED** [review]
# Status: PROJECT APPROVED :+1: :100: :1st_place_medal: 
 ### Hi, congratulations on completing your project, very good job.
**Please do not forget for the next time to request the pull request from the feature branch to the development branch and not main branch**

_Do not forget to submit a completion form_

### HAPPY CODING :computer:

**Pull request merged**
